### ISSUE TITLE
Update Jumbotron on Intake and Tip Django Files

### ISSUE THREAD

**Issue by bocaaust** [bocaaust/CrowdCop#11]
Retooled the code on the jumbotrons used on those pages to work better with all screen resolutions. Please update the django files accordingly.

**Comment by kburk1997** [comment]
I just pushed a commit to update the jumbotron on the intake and tip django files.
I also created a "parent" template for all forms so that any future changes to the jumbotron will affect all pages using the jumbotron, thus avoiding any repeated code.
Still having issues with static files, so I uploaded the images to a secure host.
